language: java
sudo: required
services:
  - docker
script: mvn checkstyle:check clean install javadoc:javadoc cobertura:cobertura -Ptest cobertura:cobertura-integration-test

after_success: 
- bash <(curl -s https://codecov.io/bash)
