language: java
sudo: required
services:
  - docker
script:
  - mvn clean install -DskipTests
  - mvn checkstyle:check
  - mvn test cobertura:cobertura
  - mvn javadoc:javadoc
  - mvn -PdockerIT -Ddb=postgres
  - mvn -PdockerIT -Ddb=h2
  - mvn -PdockerIT -Ddb=mysql

after_success: 
- bash <(curl -s https://codecov.io/bash)
